# Generated by Django 6.0.2 on 2026-02-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='joined_at',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
