# Generated by Django 6.0.2 on 2026-02-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_session_joined_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
